<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RestaurantOps.Models\RestaurantOps.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Build this class library using .NET 8. -->
    <TargetFramework>net8.0</TargetFramework>

    <!-- Automatically imports common namespaces such as
         System, System.Collections.Generic, and System.Threading.Tasks. -->
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Enables compiler warnings for possible null-reference problems. -->
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>